version: '3'

services:
  mkdocs:
    image: ghcr.io/peaceiris/mkdocs-material:latest
    container_name: mkdocs
    ports:
      - 8150:8000
    volumes:
      - ${PWD}:/root
    stdin_open: true
    tty: true
    command:
      - "mkdocs"
      - "serve"
      - "--dev-addr=0.0.0.0:8000"
      - "--config-file"
      - "./mkdocs.yml"
